version: "3.9"
services:
  app:
    image: binly
    platform: "linux/amd64"
    working_dir: /app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_URL=${DATABASE_URL}"
      - "NEXTAUTH_SECRET=${NEXTAUTH_SECRET}"
      - "NEXTAUTH_URL=${NEXTAUTH_URL}"
      - "GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}"
      - "GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}"
