version: "3.9"
services:
  app:
    image: binly
    platform: "linux/amd64"
    build:
      context: .
      args:
        NEXT_PUBLIC_CLIENTVAR: "clientvar"
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - "DATABASE_URL=${DATABASE_URL}"
